### ISSUE TITLE
Cannot deserialize instance of `long[]` out of START_OBJECT token

### ISSUE THREAD

**Issue by trongcauhcmus** [EOSEssentials/eos-java-rpc-wrapper#25]
When i running get action. and get the exception
```Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `long[]` out of START_OBJECT token
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 6446] (through reference chain: client.domain.response.history.action.Actions["actions"]->java.util.ArrayList[5]->client.domain.response.history.action.Action["action_trace"]->client.domain.common.ActionTrace["account_ram_deltas"]->long[][0])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1342)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1138)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1092)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseLongPrimitive(StdDeserializer.java:320)
	at com.fasterxml.jackson.databind.deser.std.PrimitiveArrayDeserializers$LongDeser.deserialize(PrimitiveArrayDeserializers.java:771)
	at com.fasterxml.jackson.databind.deser.std.PrimitiveArrayDeserializers$LongDeser.deserialize(PrimitiveArrayDeserializers.java:723)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1611)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1203)
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:32)
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:23)
	at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:122)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:217)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
	at client.impl.EosApiServiceGenerator.executeSync(EosApiServiceGenerator.java:40)
	... 3 more
```

**Comment by trongcauhcmus** [comment]
in `account_ram_deltas` it is the list of `object`, not `long`

**Comment by Fletch153** [comment]
Fixed.
