### ISSUE TITLE
get action api error

### ISSUE THREAD

**Issue by yangqihua** [EOSEssentials/eos-java-rpc-wrapper#31]
Exception in thread "main" client.exception.EosApiException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "context_free" (class client.domain.common.ActionTrace), not marked as ignorable (8 known properties: "trx_id", "act", "inline_traces", "console", "receipt", "cpu_usage", "elapsed", "total_cpu_usage"])
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 1381] (through reference chain: client.domain.response.history.action.Actions["actions"]->java.util.ArrayList[0]->client.domain.response.history.action.Action["action_trace"]->client.domain.common.ActionTrace["context_free"])
	at client.impl.EosApiServiceGenerator.executeSync(EosApiServiceGenerator.java:48)
	at client.impl.EosApiRestClientImpl.getActions(EosApiRestClientImpl.java:217)
	at io.eos8.server.wrapper.ActionTest.getActions(ActionTest.java:60)
	at io.eos8.server.wrapper.ActionTest.main(ActionTest.java:37)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "context_free" (class client.domain.common.ActionTrace), not marked as ignorable (8 known properties: "trx_id", "act", "inline_traces", "console", "receipt", "cpu_usage", "elapsed", "total_cpu_usage"])
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 1381] (through reference chain: client.domain.response.history.action.Actions["actions"]->java.util.ArrayList[0]->client.domain.response.history.action.Action["action_trace"]->client.domain.common.ActionTrace["context_free"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:60)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:822)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1152)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1589)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1567)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1611)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1203)
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:32)
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:23)
	at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:122)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:217)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
	at client.impl.EosApiServiceGenerator.executeSync(EosApiServiceGenerator.java:40)
	... 3 more

Process finished with exit code 1

**Comment by yangqihua** [comment]
use mainnet node: https://eos.greymass.com

**Comment by hiluoyun** [comment]
I have the same problem.
