### ISSUE TITLE
Unrecognized field "server_version_string"

### ISSUE THREAD

**Issue by wushbin** [EOSEssentials/eos-java-rpc-wrapper#33]
Error is as below:
```
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "server_version_string"



Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "server_version_string" (class client.domain.response.chain.ChainInfo), not marked as ignorable (12 known properties: "block_cpu_limit", "head_block_producer", "head_block_num", "block_net_limit", "chain_id", "head_block_id", "head_block_time", "virtual_block_net_limit", "last_irreversible_block_id", "last_irreversible_block_num", "virtual_block_cpu_limit", "server_version"])
        at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 582] (through reference chain: client.domain.response.chain.ChainInfo["server_version_string"])
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:822)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1152)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1582)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1560)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
        at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1611)
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1203)
        at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:32)
        at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:23)
        at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:122)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:217)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall.execute(ExecutorCallAdapterFactory.java:91)
        at client.impl.EosApiServiceGenerator.executeSync(EosApiServiceGenerator.java:40)
        at client.impl.EosApiRestClientImpl.getChainInfo(EosApiRestClientImpl.java:48) 
        at sharkwallet.blockfish.io.sharkwallet.WalletFragment$pushTransaction.doInBackground(WalletFragment.java:259) 
        at sharkwallet.blockfish.io.sharkwallet.WalletFragment$pushTransaction.doInBackground(WalletFragment.java:252) 
        at android.os.AsyncTask$2.call(AsyncTask.java:333) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 

```

My code:
```
EosApiRestClient eosApiRestClient = EosApiClientFactory.newInstance(burl).newRestClient();

ChainInfo chainInfo = eosApiRestClient.getChainInfo();

Log.v(TAG+"/chain", gson.toJson(chainInfo));
```

Could anyone help me fix this?
BTW, I used it in android studio.

**Comment by wushbin** [comment]
In gradle file, change from 
````
implementation 'com.github.EOSEssentials:eos-java-rpc-wrapper:master'
````
to 
````
implementation 'com.github.EOSEssentials:eos-java-rpc-wrapper:master-SNAPSHOT' 
````
