### ISSUE TITLE
okhttp error end of stream

### ISSUE THREAD

**Issue by srmcatee1110** [EOSEssentials/eos-java-rpc-wrapper#40]
Caused by: java.io.EOFException: \n not found: limit=0 content=…
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:237)
	at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)

The code:
`
import client.EosApiClientFactory;
import client.EosApiRestClient;
import client.domain.response.chain.AbiJsonToBin;

import java.util.HashMap;
import java.util.Map;

public class Main {

    public static void main(String[] args) {

        EosApiRestClient eosApiRestClient;
        eosApiRestClient = EosApiClientFactory.newInstance("http://127.0.0.1:8888").newRestClient();

        //build payload
        Map<String, String> arg = new HashMap(4);
        arg.put("custacct", "consumer");
        arg.put("account", "fimulti");
        arg.put("name", "onboard");

        AbiJsonToBin data = eosApiRestClient.abiJsonToBin("currency", "transfer", arg);

`

**Comment by Cavan2477** [comment]
You should add following items in pom.xml for initialize eos_api_rest_client

`<properties>
        <com.squareup.retrofit2.version>2.5.0</com.squareup.retrofit2.version>
        <converter-scalars.version>2.5.0</converter-scalars.version>
        <okhttp.version>3.12.0</okhttp.version>
    </properties>

<dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>${okhttp.version}</version>
        </dependency>
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>logging-interceptor</artifactId>
            <version>${okhttp.version}</version>
        </dependency>
        <dependency>
            <groupId>com.squareup.retrofit2</groupId>
            <artifactId>converter-scalars</artifactId>
            <version>${converter-scalars.version}</version>
        </dependency>
        <dependency>
            <groupId>com.squareup.retrofit2</groupId>
            <artifactId>retrofit</artifactId>
            <version>${com.squareup.retrofit2.version}</version>
        </dependency>`
